housePLAN/Controllers/SearchController.cs
using housePLAN.Data;
using housePLAN.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace housePLAN.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SearchController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: PropertyAddresses
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Results(Models.VM.SearchPropertyVM model)
        {
            if (string.IsNullOrEmpty(model.Postcode) && string.IsNullOrEmpty(model.Street))
            {
                return Redirect(nameof(Index));
            }

            var abdata = _context.AddressBaseItems.AsQueryable();
            if (!string.IsNullOrEmpty(model.Postcode))
            {
                string pc = model.Postcode.Replace(" ", "").ToUpper();
                abdata = abdata.Where(i => i.PostcodeTrimmed == pc);
            }
            if (!string.IsNullOrEmpty(model.Street))
            {
                abdata = abdata.Where(i => i.DEPENDENT_THOROUGHFARE.Contains(model.Street));
            }

            var abdataResults = await abdata.Take(100).OrderBy(i=>i.BUILDING_NUMBER).ToListAsync();
            var data = new List<housePLAN.Models.VM.PropertyAddressVM>();

            var fa = await _context.FileAttachments.Where(i => abdata.Select(s => s.Id).Contains(i.AddressBaseItemId)).Select(s => s.AddressBaseItemId).Distinct().ToListAsync();

            foreach (var item in abdataResults)
            {
                data.Add(new Models.VM.PropertyAddressVM()
                {
                    Address = item,
                    HasFiles = fa.Where(i=>i == item.Id).Any()
                });
            }
            return View(data);
        }
    }
}

housePLAN/Views/Search/Index.cshtml
@model housePLAN.Models.VM.SearchPropertyVM
@{
    ViewData["Title"] = "Home Page";
}

<div class="search-wrapper ">

    <div class=" col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2  text-center" style="background-color:none;">
        

        <p class="font-weight-bold alert alert-warning">
            Please enter a postcode or street to continue
        </p>

    </div>

    <form asp-action="Results" asp-controller="Search" method="get" class="container bg-white p-2">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <dl class="row">

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Postcode)
            </dt>
            <dd class="col-sm-6">
                <input asp-for="Postcode" class="form-control" />
                <span asp-validation-for="Postcode" class="text-danger"></span>
            </dd>

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Street)
            </dt>
            <dd class="col-sm-6">
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </dd>


            <div class="col-sm-6 offset-sm-3 mt-5">
                <button class="btn btn-success btn-block">Show Results</button>
            </div>

        </dl>
    </form>

</div>

<script>
    document.getElementsByClassName('container')[1].classList.remove('container').add('container-fluid');
</script>

housePLAN/Views/Search/Results.cshtml
@model IEnumerable<housePLAN.Models.VM.PropertyAddressVM>

@{
    ViewData["Title"] = "Results";
}

<h1>Search Results</h1>

<p class="border-bottom">

    @{
        string text = Model.Count() == 1 ? "1 entry" : Model.Count() + " entries";
    }
    Found @text for your search
</p>

@foreach (var item in Model)
{
    <div class="search-result">
        <div class="row">
            <div class="col">
                <h1>@item.FullAddressPretty</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-6">
                <h2>Detailed Address</h2>
                <dl class="row">

                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Address.BUILDING_NUMBER)
                    </dt>
                    <dd class="col-sm-6">
                        @item.Address.BUILDING_NUMBER
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Address.DEPENDENT_THOROUGHFARE)
                    </dt>
                    <dd class="col-sm-6">
                        @item.Address.DEPENDENT_THOROUGHFARE
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Address.DEPENDENT_LOCALITY)
                    </dt>
                    <dd class="col-sm-6">
                        @item.Address.DEPENDENT_LOCALITY
                    </dd>
                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Address.POST_TOWN)
                    </dt>
                    <dd class="col-sm-6">
                        @item.Address.POST_TOWN
                    </dd>

                    <dt class="col-sm-6">
                        @Html.DisplayNameFor(model => model.Address.POSTCODE)
                    </dt>
                    <dd class="col-sm-6">
                        @item.Address.POSTCODE
                    </dd>
                </dl>
            </div>


            <div class="col-12 col-sm-6">
                <h2>Available Files</h2>

                <div>
                    @if (item.HasFiles)
                    {
                        <img src="/img/plans.svg" data-toggle="modal" data-target="#exampleModal" data-abid="@item.Address.Id" class="img-fluid" width="150" />
                    }
                    else
                    {
                        <img src="~/img/no-photo.svg" class="img-fluid" width="150" />
                    }
                </div>

                @*<dl class="row">
                        <dt class="col-sm-6">housePLAN 1a.PDF</dt>
                        <dd class="col-sm-6"><a href="/housePLAN 1a.PDF">Download</a></dd>
                        <dt class="col-sm-6">housePLAN 1b.PDF</dt>
                        <dd class="col-sm-6"><a href="/housePLAN 1b.PDF">Download</a></dd>
                        <dt class="col-sm-6">housePLAN 1c.PDF</dt>
                        <dd class="col-sm-6"><a href="/housePLAN 1c.PDF">Download</a></dd>
                    </dl>*@
            </div>
        </div>
    </div>
}










@*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Open modal for @mdo</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@fat">Open modal for @fat</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@getbootstrap">Open modal for @getbootstrap</button>*@

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Available Files</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal-body">
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Recipient:</label>
                        <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $('#exampleModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget) // Button that triggered the modal
            var abid = button.data('abid') // Extract info from data-* attributes
            // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
            // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
            var modal = $(this)
            modal.find('.modal-body').load('/downloadplans/listdocs/' + abid);
        })
    </script>
}